title: Mickael Bettinelli
email: mickael.bettinelli@lcis.grenoble-inp.fr
description: A collective intelligence approach for reuse-oriented decision support in circular design and remanufacturing
github_username:  MilowB
theme: jekyll-theme-tactile
